### ISSUE TITLE
`--edit` じゃなくて `--overwrite` ?

### ISSUE THREAD

**Issue by book000** [jaoafa/DynmapProcessor#8]
「既存のファイルを編集」というより「上書き」の方が正しいかなあと。前者の場合、outputにあるファイルを「元として」ファイルをいじるイメージを与えるような。

**Comment by yuuahp** [comment]
--edit は編集機能を有効化するためのフラグだから上書きとかは関係ないかも

**Comment by book000** [comment]
あれ、そうなの？だとすると `edit` の意味が微妙にわからんっちゃわからんな…

**Comment by book000** [comment]
とりあえずまあそういうアレなら違うのでclose
